# Insert blank line between shell prompts
add_newline = true

# prompt format
format = """$python $username$hostname$directory$git_branch$git_status${custom.writing}${custom.dev}
$character"""

[username]
style_user = "fg:#929be5 bg:#282b39"
style_root = "fg:#b871b8 bg:#282b39"
format = "[$user]($style) "
disabled = false
show_always = true

[directory]
format = "[$path]($style) [$read_only]($read_only_style)"
read_only = ""
read_only_style = "#dc6f7a"
style = "fg:#a8a384 bg:#282b39"
truncation_length = 3
truncation_symbol = ".../"
truncate_to_repo = false
disabled = false
home_symbol = ""

[character]
format = "$symbol "
success_symbol = "[»](#7cbe8c)"
error_symbol = "[»](#dc6f7a)"
disabled = false

[custom.dev]
format = "[$symbol]($style)"
when = "pwd | rg -i 'Dev'"
symbol = " "
style = "#59b6b6"

[custom.writing]
format = "[$symbol]($style)"
when = "pwd | rg -i 'Writing'"
symbol = " "
style = "#59b6b6"


[git_branch]
always_show_remote = false
format = "[$symbol$branch]($style) "
symbol = ":"
style = "#b871b8"
only_attached = false
disabled = false

[git_status]
conflicted = "»«"
ahead = "⇡"
behind = "⇣"
diverged = "⇕"
stashed = "$"
modified = "!"
staged = "+"
renamed = "易"
deleted = "x"
style = "#dc6f7a"
disabled = false

[hostname]
ssh_only = true
format = "[$hostname]($style)"
style = "fg:#929be5 bg:#282b39"
disabled = false

[python]
format = "[$virtualenv]($style)"
style = "#59b6b6"
